[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v

[coverage:run]
source = .
omit = 
    tests/*
    */site-packages/*
    preprocess_lib/*
    preprocess.py
    create_exp.py
branch = True
