[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
filterwarnings =
    ignore::UserWarning:torch.__config__
    ignore::DeprecationWarning:torch.jit._script
    ignore::DeprecationWarning:torch_geometric.llm.utils.backend_utils

[coverage:run]
source = .
omit = 
    tests/*
    */site-packages/*
    preprocess_lib/*
    preprocess.py
    create_exp.py
branch = True
